#!/usr/bin/env ruby

require 'rubygems'
require 'fileutils'
require 'plist'
require 'term/ansicolor'
require 'tmpdir'
require 'yaml'

include Term::ANSIColor

# Main block

def main
  banner
  check_args
  setup
  print_config
  Dir.mkdir $config['tmp_dir']

  FileUtils.mkdir_p '.babelyoda', :verbose => true

  eval $config['action']

  FileUtils.rm_rf $config['tmp_dir'], :verbose => true
  success "All done!"
end

# Aux methods

def banner
  puts "Babel Yoda v1.0"
  puts "© 2010 Andrey Subbotin <andrey@subbotin.me>"
end

def usage 
  puts ""
  puts "Usage: babelyoda <action> [<rules.babelyoda>]"
  puts ""
  puts "<action>          = push | pull"
  puts "<rules.babelyoda> = babel yoda config file, default is rules.babelyoda"   
end

def check_args 
  if (ARGV.length == 0)
    usage
    exit 1
  elsif (ARGV.length == 1)
    unless (ARGV[0] == 'push' || ARGV[0] == 'pull')
      usage
      exit 1
    end
  end
end

def setup
  $config = Hash.new
  global_config_filename = File.expand_path('~/.babelyoda')
  $config.merge!(YAML.load_file(global_config_filename)) if File.exist?(global_config_filename)
  config = YAML.load_file(ARGV[1].nil? ? 'rules.babelyoda' : ARGV[1])
  config['tmp_dir'] = File.join Dir.tmpdir, "epl.babelyoda.#{$$}"
  config['src_dir'] = File.join config['tmp_dir'], 'src'
  config['startwd'] = Dir.getwd
  config['action'] = ARGV[0]
  config['src_lang'] = Plist::parse_xml(config['plist'])['CFBundleDevelopmentRegion']
  config['src_lang_lproj'] = config['src_lang'] + '.lproj'
  config['src_lang_lproj_dir'] = File.join(config['target_dir'], config['src_lang_lproj'])
  config['src_lang_code_strings_file'] = File.join(config['src_lang_lproj_dir'], 'Localizable.strings')
  config['initial_strings_file'] = File.join(config['target_dir'], 'Localizable.strings')
  config['src_lang_xibs_lproj_dir'] = File.join(config['target_dir'], 'XIBs', "#{config['src_lang']}.lproj")
  $config.merge!(config)
end

def print_config
  # Print out settings
  status "CONFIG"
  y $config
end

def exe(cmd)
  putcmd cmd
  system cmd
end

def putcmd(cmd)
  print magenta, "CMD: #{cmd}", reset, "\n"  
end

def status(msg)
  print blue, "--- #{msg} ---", reset, "\n"  
end

def error(msg)
  print red, bold, 'ERROR: ', msg, reset, "\n"
  exit 1
end

def success(msg)
  print green, bold, 'SUCCESS: ', msg, reset, "\n"
end

# Globbers

def all_lproj_dirs
  (dst_lproj_dirs << src_lproj_dir).sort
end

def src_lproj_dir
  $config['src_lang_lproj_dir']
end

def dst_lproj_dirs
  $config['languages'].collect{ |l| 
    lproj_dir_for_lang(l) 
  }.sort
end

def lproj_dir_for_lang(lang)
  File.join($config['target_dir'], "#{lang}.lproj")
end

def src_code_files
  $config['code_dirs'].collect{ |dir|
    Dir.glob(File.join(dir, '**', '*.{c,h,m,hh,mm}'))
  }.flatten!.sort
end

def src_code_strings_files
  Dir.glob(File.join($config['src_lang_lproj_dir'], '*.strings')).sort
end

def src_xib_files
  $config['xib_dirs'].collect{ |dir| 
    Dir.glob(File.join(dir, '**', $config['src_lang_lproj'], '*.xib')) 
  }.flatten!.sort
end

# Processing

def push
  init_lproj_dirs
  gen_src_code_strings
  gen_src_xib_strings
  init_dst_code_strings_files
end

def pull
end

def init_lproj_dirs
  status "PREPARING LPROJ DIRECTORIES"
  if File.exists?($config['initial_strings_file']) && File.exists?($config['src_lang_code_strings_file'])
    error "Both '#{$config['initial_strings_file']}' and '#{$config['src_lang_code_strings_file']}' exist!"
  end
  FileUtils.mkdir_p all_lproj_dirs, :verbose => true
end

# generate .strings file into the temporary directory
# touch the target file so it's created if it didn't exist
# and then merge it with the new file, preserving any translations made
def gen_src_code_strings
  status "GENERATING STRINGS FILE FOR THE SOURCE LANGUAGE"
  genstrings src_code_files, $config['tmp_dir']
  tmp_strings_file = File.join($config['tmp_dir'], 'Localizable.strings')
  FileUtils.touch $config['src_lang_code_strings_file']
  merge_strings_at_into tmp_strings_file, $config['src_lang_code_strings_file']
end

def genstrings(files, output_path)
  files_safe = escape_cmd_args(files)
  rc = exe "genstrings -o '#{output_path}' #{files_safe}"
  error "Failed to generate strings" unless rc
end

def escape_cmd_args(args)
  args.collect{ |arg| "'#{arg}'"}.join(' ')
end

def gen_src_xib_strings
  status "GENERATING STRINGS FILES FOR THE SOURCE LANGUAGE XIBS"
  src_xib_files.each do |xib|
    strings = xib.slice(0, xib.length - 4) + '.strings'
    rc = exe "ibtool --generate-strings-file '#{strings}' '#{xib}'"
    error "Failed to generate strings for file '#{xib}'" unless rc
  end
end

def init_dst_code_strings_files
  status "BOOTSTRAPPING LOCALIZED STRINGS FILES FOR THE TARGET LANGUAGES"
  src_code_strings_files.each do |src_file|
    dst_lproj_dirs.each do |dst_lproj_dir|
      dst_file = File.join(dst_lproj_dir, File.split(src_file).last)
      FileUtils.cp(src_file, dst_file, :preserve => true, :verbose => true)
    end
  end
end

def merge_strings_at_into(src_strings, dst_strings)
  status "MERGING STRINGS AT '#{src_strings}' INTO '#{dst_strings}'"
  rc = exe "wincent-strings-util --base '#{src_strings}' --merge '#{dst_strings}' --output '#{dst_strings}'"
  error "Failed to merge '#{src_strings}' into '#{dst_strings}'" unless rc
end

main
exit 0
